name: Push to Production
on:
  workflow_dispatch:
        

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  BUCKET_NAME: "website-kris-2024"
  AWS_REGION: "us-east-1"
  DISTRIBUTION_ID: "E28HYIC467JMDM"

jobs: 
  upload_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install boto3
        run: pip install boto3

      - name: Upload Files to Prod Bucket
        working-directory: .github/ci_scripts
        run: python upload_files_to_bucket.py

  invalidate_cache:
    needs: [upload_files]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install boto3
        run: pip install boto3

      - name: Invalidate CloudFront Cache
        working-directory: .github/ci_scripts
        run: python invalidate_cache.py