name: Upload Files to Dev Bucket
on:
    pull_request:
        branches:
            - main
        paths-ignore:
            - 'README.md'
            - '.gitignore'

env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    BUCKET_NAME: "website-kris-2024-dev"
    AWS_REGION: "us-east-1"

jobs: 
    upload_files:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install boto3
              run: pip install boto3

            - name: Upload Files to Dev Bucket
              working-directory: .github/ci_scripts
              run: python upload_files_to_bucket.py

            - name: Check Dev URL
              run: echo "http://$BUCKET_NAME.s3-website-$AWS_REGION.amazonaws.com/"
              