name: Upload Files to Dev Bucket
on:
    pull_request:
        branches:
            - main
        paths-ignore:
            - 'README.md'
            - '.gitignore'

env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs: 
    upload_files:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install boto3
              run: pip install boto3

            - name: Upload Files to Dev Bucket
              working-directory: .github/ci_scripts
              run: python upload_files_to_dev.py
              